AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-typescript-webpack

    Sample SAM Template for sam-typescript-webpack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Runtime: nodejs16.x
        Timeout: 300

Resources:
    AuthFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: build/auth
            Handler: auth.handler
            Events:
                SignIn:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /auth/sign-in
                        Method: post
                Refresh:
                    Type: Api
                    Properties:
                        Path: /auth/refresh
                        Method: get
    UserFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: build/user
            Handler: user.handler
            Events:
                Detail:
                    Type: Api
                    Properties:
                        Path: /user
                        Method: get
                Projects:
                    Type: Api
                    Properties:
                        Path: /user/projects
                        Method: get

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    AuthApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/'
    UserApi:
        Description: 'API Gateway endpoint URL for Prod stage for Goodbye function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/'
